-- Working Knowledge loot pools.
--
-- One pool per procedural distribution. Each pool registers a single
-- placeholder item into that distribution (see WK_Distributions.lua); once the
-- container is filled, WK_LootReplace.lua swaps the placeholder for a random
-- document drawn from `docs`.
--
-- `weight` is the whole pool's spawn weight, not a per-document weight. In
-- ItemPickerJava every list entry is rolled independently once per container
-- roll, and weight is effectively a percent chance, so the expected number of
-- WK documents in a container is  rolls * weight / 100.  Adding or removing
-- documents from `docs` therefore does not change how often one spawns, only
-- which ones can.
--
-- Every weight is derived from one of three tiers rather than tuned by hand:
--
--   generic   1 document per 6 containers     furniture found across many
--                                             unrelated building types
--   specific  1 document per 3 containers     tied to one trade or building
--                                             type that is reasonably common
--   rare      1 document per 1.5 containers   tied to one trade or building
--                                             type that is scarce map-wide
--
--   weight = 100 / (containersPerDocument * rolls)
--
-- The tiers exist because a flat per-container rate is not an encounter rate:
-- a generic filing cabinet appears thousands of times on the map, a pottery
-- studio a handful. Scarcer containers need a higher hit rate to stay findable.
--
-- These values were doubled in 1.1. The 12/6/3 used in 1.0 measured out around
-- 4x rarer than 0.9 for the containers players actually open, which is not what
-- that release intended.
--
-- Other mods can retune or extend this without overwriting the file:
--
--     local pools = require "WK_LootPools"
--     table.insert(pools.list.OfficeDesk.docs, "MyMod_ExpenseReport")
--     pools.list.FilingCabinetGeneric.weight = 4.0

local WK_LootPools = {}

WK_LootPools.list = {

    ArmySurplusLiterature = {
        placeholder = "WK_Doc_ArmySurplusLiterature",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_VietnamRiflemanNotes",
            "WK_NavalGunnersManual",
            "WK_GuardForceWeaponsManual",
            "WK_CombatShootingDrills",
            "WK_TacticalReloadRef",
            "WK_WWIIBayonetTraining",
            "WK_ArmyAPFTManual",
            "WK_ArmyCombatMedic",
            "WK_ArmyCombatLifter",
            "WK_NavySEALReconPamph",
            "WK_SARTrackingTraining",
            "WK_ArmyMessHallSOP",
        },
    },

    ArmyBunkerLockers = {
        placeholder = "WK_Doc_ArmyBunkerLockers",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_ArmyAPFTManual",
            "WK_ArmyCombatLifter",
            "WK_VietnamRiflemanNotes",
            "WK_ArmyCombatMedic",
            "WK_NavySEALReconPamph",
        },
    },

    ArmyBunkerStorage = {
        placeholder = "WK_Doc_ArmyBunkerStorage",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_NavalGunnersManual",
            "WK_ArmyCombatMedic",
            "WK_GuardForceWeaponsManual",
        },
    },

    PoliceFilingCabinet = {
        placeholder = "WK_Doc_PoliceFilingCabinet",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_KCPDFirearmsQual",
            "WK_RangeSafetyOfficerRef",
            "WK_DefensiveHandgunRef",
            "WK_SheriffQualLog",
            "WK_TacticalReloadRef",
            "WK_MagazineDrillCard",
            "WK_ArmorersWeaponsRef",
            "WK_ImpactWeaponMaintSOP",
            "WK_KCPDImpactWeaponsRef",
            "WK_LEFitnessStandardsRef",
            "WK_NRAPistolInstructorMan",
            "WK_KYConcealedCarryGuide",
            "WK_FBIQualScorebook",
            "WK_PoliceAcademyHandgun",
            "WK_RevolverSpeedloaderCard",
            "WK_RangemasterDrillBook",
            "WK_NightstickTrainingMan",
            "WK_RiotBatonInstructorRef",
            "WK_PoliceRecruitFitness",
            "WK_BloodhoundHandlerCard",
        },
    },

    PoliceDesk = {
        placeholder = "WK_Doc_PoliceDesk",
        weight      = 16.6667,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_KCPDFirearmsQual",
            "WK_DefensiveHandgunRef",
            "WK_TacticalReloadRef",
            "WK_MagazineDrillCard",
            "WK_ImpactWeaponMaintSOP",
            "WK_KCPDImpactWeaponsRef",
            "WK_PoliceAcademyHandgun",
            "WK_CombatShootingDrills",
            "WK_PoliceRecruitFitness",
        },
    },

    FireStorageTools = {
        placeholder = "WK_Doc_FireStorageTools",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_ForcibleEntryRef",
            "WK_FirefighterHandToolSOP",
            "WK_CPRAEDRef",
            "WK_EmergencyTriageRef",
            "WK_FireAcademyFitnessRef",
            "WK_WorkplaceFirstAidSOP",
            "WK_EngineCompanyAxeRef",
            "WK_EMTRescueKnifeCard",
            "WK_FirefighterHaliganRef",
            "WK_PulaskiSwingScale",
            "WK_ParamedicProtocolMan",
            "WK_ArmyCombatMedic",
            "WK_SARTrackingTraining",
        },
    },

    WildWestBlacksmith = {
        placeholder = "WK_Doc_WildWestBlacksmith",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_ASTMMaterialSpecRef",
            "WK_ForgeHeatTreatGuide",
            "WK_IndustrialMetalworkRef",
            "WK_BlacksmithGuildStandards",
            "WK_ABANANewsletter",
            "WK_FarrierShoeingNotes",
            "WK_FrontierForgeRef",
            "WK_SwordsmithApprDiary",
            "WK_ColonialIronworker",
        },
    },

    MetalShopTools = {
        placeholder = "WK_Doc_MetalShopTools",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_ASTMMaterialSpecRef",
            "WK_ForgeHeatTreatGuide",
            "WK_IndustrialMetalworkRef",
            "WK_EdgeToolSharpeningRef",
            "WK_WhetstoneSelectionRef",
            "WK_BladesmithToolCare",
            "WK_KnifemakerTestCutLog",
            "WK_BlacksmithHammerCard",
            "WK_SteelmillProcessRef",
            "WK_KnifemakerForgeWeld",
            "WK_MotorControlSchem",
            "WK_NSFBladeSafetyRef",
        },
    },

    WeldingWorkshopTools = {
        placeholder = "WK_Doc_WeldingWorkshopTools",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_AWSD11WeldingRef",
            "WK_WeldingProcSpecRef",
            "WK_ElectrodeFillMetalRef",
            "WK_WeldInspectionRef",
            "WK_OSHAWeldingSafety",
            "WK_AWSCertWelderManual",
            "WK_PipefittersWelding",
            "WK_AluminumMIGRef",
            "WK_UAWWeldingShopSOP",
            "WK_StickRodSelectionGuide",
            "WK_AerospaceTIGNotes",
        },
    },

    MechanicShelfBooks = {
        placeholder = "WK_Doc_MechanicShelfBooks",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_OBDIICodeRef",
            "WK_TorqueSpecsRef",
            "WK_BrakeServiceRef",
            "WK_AutoElecDiagRef",
            "WK_FleetMaintenanceLog",
            "WK_AutoBodyHammerNotes",
            "WK_ASEStudyGuide",
            "WK_KYVehicleInspection",
            "WK_BriggsStrattonRepair",
            "WK_DieselTroubleshoot",
            "WK_FordPickupShopMan",
            "WK_ChevyTechServiceBull",
            "WK_AutoBodyWeldingRef",
        },
    },

    CarDealerFilingCabinet = {
        placeholder = "WK_Doc_CarDealerFilingCabinet",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_OBDIICodeRef",
            "WK_TorqueSpecsRef",
            "WK_FleetMaintenanceLog",
            "WK_ASEStudyGuide",
            "WK_ChevyTechServiceBull",
            "WK_TruckingFleetPMSched",
        },
    },

    ElectricianTools = {
        placeholder = "WK_Doc_ElectricianTools",
        weight      = 11.1111,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_NECArticleRef",
            "WK_WireGaugeAmpacityRef",
            "WK_OSHAElectricalSafety",
            "WK_ConduitFillRef",
            "WK_PanelInspectionChecklist",
            "WK_IBEWApprentBook",
            "WK_ResWiringText",
            "WK_MotorControlSchem",
            "WK_TransformerNamePlate",
            "WK_GroundingBondingRef",
            "WK_KYStateLicensingMan",
            "WK_UndergroundCableRef",
        },
    },

    ToolCabinetFarming = {
        placeholder = "WK_Doc_ToolCabinetFarming",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_KnoxExtensionGuide",
            "WK_SoilTestInterpretRef",
            "WK_PesticideApplicationRef",
            "WK_IrrigationSchedulingRef",
            "WK_LivestockHealthRef",
            "WK_VaccinationDosageRef",
            "WK_KDALivestockRef",
            "WK_BushHogOperatorRef",
            "WK_CornDetasselingCard",
            "WK_KaiserBladeFieldRef",
            "WK_FarrierShoeingNotes",
            "WK_KYExtensionCookbook",
            "WK_BriggsStrattonRepair",
            "WK_FFAVocAgText",
            "WK_KYExtensionAgBull",
            "WK_FertSpreaderCalCard",
            "WK_USDACropRotation",
            "WK_NoTillFarmingMan",
            "WK_KYTobaccoGrowGuide",
            "WK_KYCattlemensNews",
            "WK_FFALivestockJudging",
            "WK_TysonPoultryGrower",
            "WK_SheepGoatBreeder",
            "WK_SwineProductionMan",
            "WK_DairyHerdMgmt",
            "WK_DeerProcessorGuide",
            "WK_WildGameProcessor",
            "WK_FarmStrengthManual",
            "WK_KYWildflowerGuide",
            "WK_USDAAnimalDamage",
        },
    },

    ButcherLiterature = {
        placeholder = "WK_Doc_ButcherLiterature",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_USDAMeatGradingRef",
            "WK_PrimalSubPrimalRef",
            "WK_HACCPMeatProcessing",
            "WK_MeatFabricationRef",
            "WK_ButchersBoningGuide",
            "WK_UFCWCutleryTechRef",
            "WK_UnionStockyardsCut",
            "WK_DeerProcessorGuide",
            "WK_SausageProductionNotes",
            "WK_SmallSlaughterhouseSOP",
            "WK_KosherButcheringRef",
            "WK_CharcuterieProduction",
            "WK_HolidayTurkeyCard",
            "WK_CharcutierApprDiary",
            "WK_WildGameProcessor",
            "WK_FishFabricationRef",
            "WK_SauceStockLog",
        },
    },

    ToolStoreMisc = {
        placeholder = "WK_Doc_ToolStoreMisc",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_FramingHammerCard",
            "WK_CrowbarApplicationsRef",
            "WK_FramingSquareCard",
            "WK_EdgeToolSharpeningRef",
            "WK_WhetstoneSelectionRef",
            "WK_WoodenHandleShaftRef",
            "WK_KnifeHandleFittingRef",
            "WK_MortarMixRef",
            "WK_HandToolConditionRef",
            "WK_OSHAHandToolSafety",
            "WK_TimberCruiserHandbook",
            "WK_AppalachianFellingNotes",
            "WK_MountainRescueIceAxe",
            "WK_BackcountryHatchetCard",
            "WK_TechnicalRescueAxeRef",
            "WK_KaiserBladeFieldRef",
            "WK_JewelersFileCard",
            "WK_ShopApprenticeToolLog",
            "WK_BowSawSetGuide",
            "WK_ProductionFramerCard",
            "WK_MasonsHammerRef",
            "WK_RoofersFlashingCard",
            "WK_LandClearingMaul",
            "WK_BIATraditionalBrick",
            "WK_StonecutterApprenNote",
            "WK_ConcreteFinishersRef",
            "WK_FieldstoneWalls",
            "WK_PavingStoneInstall",
            "WK_CabinetmakerJoinery",
            "WK_RoofFramingCalcCard",
            "WK_LogHomeBuildersRef",
            "WK_FurnitureMakerNotes",
            "WK_ArboristFieldGuide",
            "WK_BrushClearingRef",
            "WK_MacheteUseGuide",
            "WK_ForestryContractorSOP",
            "WK_DemolitionHandToolRef",
            "WK_FieldExpedientToolRef",
            "WK_TrapperBoneToolRef",
            "WK_ArchaeologicalToolNotes",
        },
    },

    FishingStoreGear = {
        placeholder = "WK_Doc_FishingStoreGear",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_FishIdentificationRef",
            "WK_RiggingTackleRef",
        },
    },

    PlumbingSupplies = {
        placeholder = "WK_Doc_PlumbingSupplies",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_PlumbingQuickClearRef",
        },
    },

    OfficeDesk = {
        placeholder = "WK_Doc_OfficeDesk",
        weight      = 4.1667,  -- generic tier, ~1 per 6 containers
        docs = {
            "WK_WorkplaceFirstAidSOP",
            "WK_CPRAEDRef",
            "WK_OSHAHandToolSafety",
            "WK_OSHAElectricalSafety",
            "WK_OSHAFirstAidRef",
            "WK_NIOSHLiftingRef",
            "WK_ManualMaterialsHandRef",
            "WK_FreightDockLiftCard",
            "WK_FleetMaintenanceLog",
            "WK_KYVehicleInspection",
        },
    },

    OfficeDeskHome = {
        placeholder = "WK_Doc_OfficeDeskHome",
        weight      = 4.1667,  -- generic tier, ~1 per 6 containers
        docs = {
            "WK_GolfSwingRef",
            "WK_BaseballSwingRef",
            "WK_SprintIntervalCard",
            "WK_CrossCountryRef",
            "WK_WorkplaceFirstAidSOP",
            "WK_PediatricFirstAid",
            "WK_KYFishingRegs",
            "WK_KYBassFishingClub",
        },
    },

    OfficeDeskHomeClassy = {
        placeholder = "WK_Doc_OfficeDeskHomeClassy",
        weight      = 4.1667,  -- generic tier, ~1 per 6 containers
        docs = {
            "WK_GolfSwingRef",
            "WK_BullseyeMatchProgramme",
            "WK_BostonMarathonTrain",
            "WK_NCAAStrengthCondition",
            "WK_OlympicLiftingNotes",
            "WK_NIOSHLiftingRef",
            "WK_FleetMaintenanceLog",
            "WK_TruckingFleetPMSched",
        },
    },

    WaitingRoomDesk = {
        placeholder = "WK_Doc_WaitingRoomDesk",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_WorkplaceFirstAidSOP",
            "WK_CPRAEDRef",
            "WK_EmergencyTriageRef",
            "WK_NursingFundamentals",
            "WK_PharmacistDispensing",
            "WK_PediatricFirstAid",
            "WK_NursingHomeCareMan",
            "WK_OSHAFirstAidRef",
        },
    },

    ClassroomDesk = {
        placeholder = "WK_Doc_ClassroomDesk",
        weight      = 16.6667,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_BoyScoutRiflery",
            "WK_BoyScoutAxemanship",
            "WK_ScoutTroopToolCare",
            "WK_ScoutCampcraftKnife",
            "WK_ScoutMetalwork",
            "WK_ScoutCarpentryMerit",
            "WK_BSAPrimitiveSurvival",
            "WK_AgEdJudgingCard",
        },
    },

    ClassroomSecondaryDesk = {
        placeholder = "WK_Doc_ClassroomSecondaryDesk",
        weight      = 16.6667,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_JuniorHighWoodshop",
            "WK_HomeEcSewingText",
            "WK_HSTrackCoachManual",
            "WK_KYHSAARulebook",
            "WK_SprintIntervalCard",
            "WK_CrossCountryRef",
            "WK_HSFootballCondition",
            "WK_BMXRacingTraining",
            "WK_HSWrestlingStrength",
            "WK_AgEdJudgingCard",
        },
    },

    BlacksmithLiterature = {
        placeholder = "WK_Doc_BlacksmithLiterature",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_ABANANewsletter",
            "WK_ForgeHeatTreatGuide",
            "WK_BlacksmithGuildStandards",
            "WK_IndustrialMetalworkRef",
            "WK_ASTMMaterialSpecRef",
            "WK_SteelmillProcessRef",
            "WK_ColonialIronworker",
            "WK_FrontierForgeRef",
            "WK_SwordsmithApprDiary",
            "WK_FarrierShoeingNotes",
        },
    },

    TailoringLiterature = {
        placeholder = "WK_Doc_TailoringLiterature",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_PatternGradingRef",
            "WK_IndustrialSewingRef",
            "WK_FiberFabricRef",
            "WK_GarmentQualityRef",
            "WK_SearsPatternCatalog",
            "WK_CarhartUnionShop",
            "WK_AlterationsTailorCard",
            "WK_HomeEcSewingText",
            "WK_TheatricalCostumeShop",
            "WK_HancockFabricsManual",
            "WK_UpholstererGuide",
            "WK_BridalSeamstressNotes",
        },
    },

    RangerBooks = {
        placeholder = "WK_Doc_RangerBooks",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_KDFWRGameMgmtRef",
            "WK_ApacheScoutTracking",
            "WK_WildlifeTrackSignRef",
            "WK_DeerMovementRef",
            "WK_SARTrackingTraining",
            "WK_TurkeyHuntingRef",
            "WK_WildlifeBiologyText",
            "WK_KDFWRTrapperRegs",
            "WK_NTAFurHandlersGuide",
            "WK_WildlifeTrappingGuide",
            "WK_FurbearerRef",
            "WK_EdiblePlantsRef",
            "WK_KYWildflowerGuide",
            "WK_WildMushroomHunt",
            "WK_HunterGatherersRef",
        },
    },

    MedicalOfficeDesk = {
        placeholder = "WK_Doc_MedicalOfficeDesk",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_WorkplaceFirstAidSOP",
            "WK_CPRAEDRef",
            "WK_EmergencyTriageRef",
            "WK_ParamedicProtocolMan",
            "WK_ERTriageTextbook",
            "WK_NursingFundamentals",
            "WK_PharmacistDispensing",
            "WK_WoundCareSuturing",
            "WK_ArmyCombatMedic",
            "WK_NursingHomeCareMan",
            "WK_PediatricFirstAid",
        },
    },

    GardenStoreMisc = {
        placeholder = "WK_Doc_GardenStoreMisc",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_KnoxExtensionGuide",
            "WK_SoilTestInterpretRef",
            "WK_PesticideApplicationRef",
            "WK_IrrigationSchedulingRef",
            "WK_KYExtensionAgBull",
            "WK_FFAVocAgText",
            "WK_RodaleOrganicPamph",
            "WK_KYTobaccoGrowGuide",
            "WK_EdiblePlantsRef",
            "WK_KYWildflowerGuide",
            "WK_BackyardForaging",
            "WK_StalkingWildAsparagus",
            "WK_UKAgEconNotes",
            "WK_HerbalPharmacyEnc",
            "WK_EthnobotanyText",
        },
    },

    DeskGeneric = {
        placeholder = "WK_Doc_DeskGeneric",
        weight      = 4.1667,  -- generic tier, ~1 per 6 containers
        docs = {
            "WK_GolfSwingRef",
            "WK_BaseballSwingRef",
            "WK_LEFitnessStandardsRef",
            "WK_BullseyeMatchProgramme",
            "WK_BoyScoutRiflery",
            "WK_HighPowerNewsletter",
            "WK_BoyScoutAxemanship",
            "WK_SCAHeavyFightCard",
            "WK_LarpFightChoreography",
            "WK_ScoutTroopToolCare",
            "WK_ScoutCampcraftKnife",
            "WK_CricketBowlersGuide",
            "WK_LacrosseCoachManual",
            "WK_HockeyStickHandling",
            "WK_SCAPolearmRef",
            "WK_TrackPoleVaultCard",
            "WK_KarateBoStaffMan",
            "WK_ScoutsPolearmDemo",
            "WK_ScoutMetalwork",
            "WK_SpoonCarvingNotes",
            "WK_ChipCarvingPattern",
            "WK_WaldenWoodcrafter",
            "WK_JuniorHighWoodshop",
            "WK_AppalachianFolkArt",
            "WK_KilnFusedJewelry",
            "WK_BeadSocietyLampwork",
            "WK_RendezvousMtnMan",
            "WK_BSAPrimitiveSurvival",
            "WK_ChildrenPotteryLesson",
            "WK_BeginnerWheelNotes",
            "WK_HomeEcSewingText",
            "WK_AgEdJudgingCard",
            "WK_HSTrackCoachManual",
            "WK_KYHSAARulebook",
            "WK_SprintIntervalCard",
            "WK_CrossCountryRef",
            "WK_HSFootballCondition",
            "WK_BMXRacingTraining",
            "WK_RugbyStrengthMan",
            "WK_HSWrestlingStrength",
            "WK_PediatricFirstAid",
            "WK_ScoutCarpentryMerit",
            "WK_StageCombatSpearRef",
            "WK_JavelinCoachingRef",
        },
    },

    FilingCabinetGeneric = {
        placeholder = "WK_Doc_FilingCabinetGeneric",
        weight      = 4.1667,  -- generic tier, ~1 per 6 containers
        docs = {
            "WK_LumberYardManual",
            "WK_SpanTablesRef",
            "WK_NDSWoodConstruction",
            "WK_FinishCarpentryNotes",
            "WK_FramingSquareCard",
            "WK_SheriffQualLog",
            "WK_FBIQualScorebook",
            "WK_BoyScoutRiflery",
            "WK_VietnamRiflemanNotes",
            "WK_NavalGunnersManual",
            "WK_GuardForceWeaponsManual",
            "WK_KnifeMaintenanceLog",
            "WK_HandToolConditionRef",
            "WK_ShopApprenticeToolLog",
            "WK_BarberRazorStropping",
            "WK_AntiqueDealerCare",
            "WK_UFCWCutleryTechRef",
            "WK_OSHALoggingRef",
            "WK_OSHAHandToolSafety",
            "WK_OSHAElectricalSafety",
            "WK_OSHAWeldingSafety",
            "WK_OSHAFirstAidRef",
            "WK_MortarMixRef",
            "WK_ASTMC90MasonryRef",
            "WK_BrickBlockInspectionRef",
            "WK_ConcreteMixRef",
            "WK_BIATraditionalBrick",
            "WK_ChimneySweepInspect",
            "WK_HistoricPointingMan",
            "WK_KCMasonsLocalNews",
            "WK_NECArticleRef",
            "WK_WireGaugeAmpacityRef",
            "WK_ConduitFillRef",
            "WK_PanelInspectionChecklist",
            "WK_IBEWApprentBook",
            "WK_GroundingBondingRef",
            "WK_KYStateLicensingMan",
            "WK_FleetMaintenanceLog",
            "WK_KYVehicleInspection",
            "WK_TruckingFleetPMSched",
            "WK_HACCPFoodSafetyPlan",
            "WK_TempTimeControlChart",
            "WK_ServSafeRef",
            "WK_LineCookStationRef",
            "WK_SullivanCulinaryText",
            "WK_KYExtensionCookbook",
            "WK_ArmyMessHallSOP",
            "WK_SchoolCafeteriaRef",
            "WK_PitBossBBQManual",
            "WK_HeritageCookbook1957",
            "WK_TruckStopGriddleNotes",
            "WK_WorkplaceFirstAidSOP",
            "WK_CPRAEDRef",
            "WK_EmergencyTriageRef",
            "WK_ParamedicProtocolMan",
            "WK_ERTriageTextbook",
            "WK_NursingFundamentals",
            "WK_PharmacistDispensing",
            "WK_ArmyCombatMedic",
            "WK_NursingHomeCareMan",
            "WK_WoundCareSuturing",
            "WK_PediatricFirstAid",
            "WK_PatternGradingRef",
            "WK_IndustrialSewingRef",
            "WK_FiberFabricRef",
            "WK_GarmentQualityRef",
            "WK_SearsPatternCatalog",
            "WK_CarhartUnionShop",
            "WK_AlterationsTailorCard",
            "WK_HomeEcSewingText",
            "WK_TheatricalCostumeShop",
            "WK_HancockFabricsManual",
            "WK_UpholstererGuide",
            "WK_BridalSeamstressNotes",
            "WK_KnoxExtensionGuide",
            "WK_SoilTestInterpretRef",
            "WK_PesticideApplicationRef",
            "WK_IrrigationSchedulingRef",
            "WK_FFAVocAgText",
            "WK_KYExtensionAgBull",
            "WK_UKAgEconNotes",
            "WK_KYTobaccoGrowGuide",
            "WK_RodaleOrganicPamph",
            "WK_LivestockHealthRef",
            "WK_VaccinationDosageRef",
            "WK_ReproductiveMgmtBinder",
            "WK_KDALivestockRef",
            "WK_KYCattlemensNews",
            "WK_TysonPoultryGrower",
            "WK_TrackVetDailyLog",
            "WK_USDAMeatGradingRef",
            "WK_HACCPMeatProcessing",
            "WK_UnionStockyardsCut",
            "WK_SmallSlaughterhouseSOP",
            "WK_CharcuterieProduction",
            "WK_LEFitnessStandardsRef",
            "WK_FireAcademyFitnessRef",
            "WK_NCAAStrengthCondition",
            "WK_BostonMarathonTrain",
            "WK_ArmyAPFTManual",
            "WK_NIOSHLiftingRef",
            "WK_ManualMaterialsHandRef",
            "WK_USPFPowerlifting",
            "WK_OlympicLiftingNotes",
            "WK_StrongmanTrainingMan",
            "WK_MuscleBuilderMag",
            "WK_ArmyCombatLifter",
            "WK_FreightDockLiftCard",
            "WK_CollegeStrengthLog",
            "WK_KYFishingRegs",
            "WK_CommercialFishingSafetyRef",
            "WK_KYBassFishingClub",
            "WK_CrappieAnglersGuide",
            "WK_KYTroutStocking",
            "WK_FlyTyingPattern",
            "WK_KYRiverCatfishing",
            "WK_WalleyeFishingRef",
            "WK_NoodlingHandfishing",
            "WK_KYMusselRegs",
            "WK_EdiblePlantsRef",
            "WK_ToxicPlantRef",
            "WK_KYWildflowerGuide",
            "WK_StalkingWildAsparagus",
            "WK_HerbalPharmacyEnc",
            "WK_WildMushroomHunt",
            "WK_BackyardForaging",
            "WK_EthnobotanyText",
            "WK_TraditionalAppPlants",
            "WK_HunterGatherersRef",
            "WK_WildEdiblesCookbook",
            "WK_KDFWRGameMgmtRef",
            "WK_ApacheScoutTracking",
            "WK_KYCoonHunting",
            "WK_SARTrackingTraining",
            "WK_TurkeyHuntingRef",
            "WK_WildlifeBiologyText",
            "WK_BowHunterCamoMan",
            "WK_NavySEALReconPamph",
            "WK_SignReadingNotes",
            "WK_TimberCruiserHandbook",
            "WK_BoyScoutAxemanship",
            "WK_BackcountryHatchetCard",
            "WK_TechnicalRescueAxeRef",
            "WK_KDFWRDeadwoodPamph",
            "WK_KYHighwayBrushControl",
            "WK_CornDetasselingCard",
            "WK_AppalachianHerbalCutting",
            "WK_StateParksTrailCrew",
            "WK_CaneCuttingManual",
            "WK_SushiChefKnifeBook",
            "WK_TaxidermistCapingRef",
            "WK_SurgeonScalpelRef",
            "WK_NorthwoodsFilletCard",
            "WK_RailroadSpikeMaul",
            "WK_CaverHammerPickRef",
            "WK_TrackMaintenanceSledge",
            "WK_KDFWRBowfishingRef",
            "WK_CherokeeFishSpear",
            "WK_WWIIBayonetTraining",
            "WK_PrimitiveSpearfishing",
            "WK_ABANANewsletter",
            "WK_SteelmillProcessRef",
            "WK_ASTMMaterialSpecRef",
            "WK_IndustrialMetalworkRef",
            "WK_WeldingProcSpecRef",
            "WK_WeldInspectionRef",
            "WK_AWSCertWelderManual",
            "WK_UAWWeldingShopSOP",
            "WK_CountryCarversBook",
            "WK_AppalachianFolkArt",
            "WK_BowyerTilleringNotes",
            "WK_CorningEngineering",
            "WK_StainedGlassChurch",
            "WK_AntiqueBottleCollect",
            "WK_TiffanyMethodRef",
            "WK_NeonSignBenders",
            "WK_CherokeeArrowhead",
            "WK_FieldArchKnapping",
            "WK_PrimBowhunterFlint",
            "WK_AmateurArchPamph",
            "WK_ObsidianSourceRef",
            "WK_KCMuseumLithicCat",
            "WK_ToolStoneQualityCard",
            "WK_LithicTechnologyRef",
            "WK_PrimitiveSkillsKnappingRef",
            "WK_LithicAnalysisStandards",
            "WK_UnivCeramicsText",
            "WK_PenlandWheelRef",
            "WK_RakuFiringNotes",
            "WK_SaltGlazeStoneware",
            "WK_AppFolkPotteryPamph",
            "WK_StudioKilnRepair",
            "WK_CommercialPotteryProc",
            "WK_KDFWRTrapperRegs",
            "WK_NTAFurHandlersGuide",
            "WK_KYBeaverTrapPamph",
            "WK_FoxHolerLureRecipes",
            "WK_ConibearSetTechnique",
            "WK_FootholdStakingRef",
            "WK_USDAAnimalDamage",
            "WK_KDFWRNuisanceWild",
            "WK_MuskratPeltStretch",
            "WK_FurAuctionGrading",
            "WK_WildlifeTrappingGuide",
            "WK_FurbearerRef",
            "WK_WildlifeTrackSignRef",
            "WK_DeerMovementRef",
            "WK_KDFWRPrimitiveWeapons",
            "WK_AtlatlSpearRef",
            "WK_WildcraftHerbalistRef",
            "WK_LogHomeBuildersRef",
            "WK_AppTimberFramePamph",
            "WK_VocSchoolBuildTrades",
            "WK_BorosilicateLampwork",
            "WK_ClayBodyFormulationRef",
            "WK_FloatGlassManufRef",
            "WK_GlassAnnealingRef",
            "WK_GlazeChemistryRef",
            "WK_GunsmithStripping",
            "WK_KilnFiringScheduleRef",
            "WK_KilnFormingRef",
            "WK_PenlandStudioGlass",
            "WK_PracticalShootingRef",
            "WK_ShotgunReloadingCard",
            "WK_USPSARulebook",
        },
    },
    -- ---------------------------------------------------------------------
    -- Skill-specific workshop, studio and locker containers. These are rare
    -- in the world and already thematically placed, so they carry a higher
    -- hit rate than the generic desk and filing cabinet pools.
    -- ---------------------------------------------------------------------

    KnappingBooks = {
        placeholder = "WK_Doc_KnappingBooks",
        weight      = 8.3333,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AmateurArchPamph",
            "WK_BSAPrimitiveSurvival",
            "WK_CherokeeArrowhead",
            "WK_FieldArchKnapping",
            "WK_KCMuseumLithicCat",
            "WK_LithicAnalysisStandards",
            "WK_LithicTechnologyRef",
            "WK_ObsidianSourceRef",
            "WK_PrimBowhunterFlint",
            "WK_PrimitiveSkillsKnappingRef",
            "WK_RendezvousMtnMan",
            "WK_ToolStoneQualityCard",
        },
    },

    KnappingTools = {
        placeholder = "WK_Doc_KnappingTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AmateurArchPamph",
            "WK_BSAPrimitiveSurvival",
            "WK_CherokeeArrowhead",
            "WK_FieldArchKnapping",
            "WK_KCMuseumLithicCat",
            "WK_LithicAnalysisStandards",
            "WK_LithicTechnologyRef",
            "WK_ObsidianSourceRef",
            "WK_PrimBowhunterFlint",
            "WK_PrimitiveSkillsKnappingRef",
            "WK_RendezvousMtnMan",
            "WK_ToolStoneQualityCard",
        },
    },

    PotteryStudioTools = {
        placeholder = "WK_Doc_PotteryStudioTools",
        weight      = 8.3333,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AppFolkPotteryPamph",
            "WK_BeginnerWheelNotes",
            "WK_ChildrenPotteryLesson",
            "WK_ClayBodyFormulationRef",
            "WK_CommercialPotteryProc",
            "WK_GlazeChemistryRef",
            "WK_KilnFiringScheduleRef",
            "WK_PenlandWheelRef",
            "WK_RakuFiringNotes",
            "WK_SaltGlazeStoneware",
            "WK_StudioKilnRepair",
            "WK_UnivCeramicsText",
        },
    },

    GlassWorkshopTools = {
        placeholder = "WK_Doc_GlassWorkshopTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AntiqueBottleCollect",
            "WK_BeadSocietyLampwork",
            "WK_BorosilicateLampwork",
            "WK_CorningEngineering",
            "WK_FloatGlassManufRef",
            "WK_GlassAnnealingRef",
            "WK_KilnFormingRef",
            "WK_KilnFusedJewelry",
            "WK_NeonSignBenders",
            "WK_PenlandStudioGlass",
            "WK_StainedGlassChurch",
            "WK_TiffanyMethodRef",
        },
    },

    CarvingWorkshopTools = {
        placeholder = "WK_Doc_CarvingWorkshopTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AppalachianFolkArt",
            "WK_ArchaeologicalToolNotes",
            "WK_BowyerTilleringNotes",
            "WK_ChipCarvingPattern",
            "WK_CountryCarversBook",
            "WK_FieldExpedientToolRef",
            "WK_JuniorHighWoodshop",
            "WK_KnifeHandleFittingRef",
            "WK_SpoonCarvingNotes",
            "WK_TrapperBoneToolRef",
            "WK_WaldenWoodcrafter",
            "WK_WoodenHandleShaftRef",
        },
    },

    CarvingWorkshopMaterials = {
        placeholder = "WK_Doc_CarvingWorkshopMaterials",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AppalachianFolkArt",
            "WK_ArchaeologicalToolNotes",
            "WK_BowyerTilleringNotes",
            "WK_ChipCarvingPattern",
            "WK_CountryCarversBook",
            "WK_FieldExpedientToolRef",
            "WK_JuniorHighWoodshop",
            "WK_KnifeHandleFittingRef",
            "WK_SpoonCarvingNotes",
            "WK_TrapperBoneToolRef",
            "WK_WaldenWoodcrafter",
            "WK_WoodenHandleShaftRef",
        },
    },

    CarpentryBooks = {
        placeholder = "WK_Doc_CarpentryBooks",
        weight      = 8.3333,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AppTimberFramePamph",
            "WK_CabinetmakerJoinery",
            "WK_FinishCarpentryNotes",
            "WK_FramingSquareCard",
            "WK_FurnitureMakerNotes",
            "WK_LogHomeBuildersRef",
            "WK_LumberYardManual",
            "WK_NDSWoodConstruction",
            "WK_RoofFramingCalcCard",
            "WK_ScoutCarpentryMerit",
            "WK_SpanTablesRef",
            "WK_VocSchoolBuildTrades",
        },
    },

    FurnitureFactoryTools = {
        placeholder = "WK_Doc_FurnitureFactoryTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AppTimberFramePamph",
            "WK_CabinetmakerJoinery",
            "WK_FinishCarpentryNotes",
            "WK_FramingSquareCard",
            "WK_FurnitureMakerNotes",
            "WK_LogHomeBuildersRef",
            "WK_LumberYardManual",
            "WK_NDSWoodConstruction",
            "WK_RoofFramingCalcCard",
            "WK_ScoutCarpentryMerit",
            "WK_SpanTablesRef",
            "WK_VocSchoolBuildTrades",
        },
    },

    BlacksmithTools = {
        placeholder = "WK_Doc_BlacksmithTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_ABANANewsletter",
            "WK_ASTMMaterialSpecRef",
            "WK_BlacksmithGuildStandards",
            "WK_ColonialIronworker",
            "WK_FarrierShoeingNotes",
            "WK_ForgeHeatTreatGuide",
            "WK_FrontierForgeRef",
            "WK_IndustrialMetalworkRef",
            "WK_KnifemakerForgeWeld",
            "WK_ScoutMetalwork",
            "WK_SteelmillProcessRef",
            "WK_SwordsmithApprDiary",
        },
    },

    BlacksmithMolds = {
        placeholder = "WK_Doc_BlacksmithMolds",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_ABANANewsletter",
            "WK_ASTMMaterialSpecRef",
            "WK_BlacksmithGuildStandards",
            "WK_ColonialIronworker",
            "WK_FarrierShoeingNotes",
            "WK_ForgeHeatTreatGuide",
            "WK_FrontierForgeRef",
            "WK_IndustrialMetalworkRef",
            "WK_KnifemakerForgeWeld",
            "WK_ScoutMetalwork",
            "WK_SteelmillProcessRef",
            "WK_SwordsmithApprDiary",
        },
    },

    TailoringTools = {
        placeholder = "WK_Doc_TailoringTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AlterationsTailorCard",
            "WK_BridalSeamstressNotes",
            "WK_CarhartUnionShop",
            "WK_FiberFabricRef",
            "WK_GarmentQualityRef",
            "WK_HancockFabricsManual",
            "WK_HomeEcSewingText",
            "WK_IndustrialSewingRef",
            "WK_PatternGradingRef",
            "WK_SearsPatternCatalog",
            "WK_TheatricalCostumeShop",
            "WK_UpholstererGuide",
        },
    },

    LeatherworkingTools = {
        placeholder = "WK_Doc_LeatherworkingTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AlterationsTailorCard",
            "WK_BridalSeamstressNotes",
            "WK_CarhartUnionShop",
            "WK_FiberFabricRef",
            "WK_GarmentQualityRef",
            "WK_HancockFabricsManual",
            "WK_HomeEcSewingText",
            "WK_IndustrialSewingRef",
            "WK_PatternGradingRef",
            "WK_SearsPatternCatalog",
            "WK_TheatricalCostumeShop",
            "WK_UpholstererGuide",
        },
    },

    CobblerTools = {
        placeholder = "WK_Doc_CobblerTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AlterationsTailorCard",
            "WK_BridalSeamstressNotes",
            "WK_CarhartUnionShop",
            "WK_FiberFabricRef",
            "WK_GarmentQualityRef",
            "WK_HancockFabricsManual",
            "WK_HomeEcSewingText",
            "WK_IndustrialSewingRef",
            "WK_PatternGradingRef",
            "WK_SearsPatternCatalog",
            "WK_TheatricalCostumeShop",
            "WK_UpholstererGuide",
        },
    },

    ClockRepairTools = {
        placeholder = "WK_Doc_ClockRepairTools",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AntiqueDealerCare",
            "WK_BarberRazorStropping",
            "WK_BladesmithToolCare",
            "WK_BowSawSetGuide",
            "WK_EdgeToolSharpeningRef",
            "WK_HandToolConditionRef",
            "WK_ImpactWeaponMaintSOP",
            "WK_JewelersFileCard",
            "WK_KnifeMaintenanceLog",
            "WK_ScoutTroopToolCare",
            "WK_ShopApprenticeToolLog",
            "WK_WhetstoneSelectionRef",
        },
    },

    ClockRepairLiterature = {
        placeholder = "WK_Doc_ClockRepairLiterature",
        weight      = 16.6667,  -- rare tier, ~1 per 1.5 containers
        docs = {
            "WK_AntiqueDealerCare",
            "WK_BarberRazorStropping",
            "WK_BladesmithToolCare",
            "WK_BowSawSetGuide",
            "WK_EdgeToolSharpeningRef",
            "WK_HandToolConditionRef",
            "WK_ImpactWeaponMaintSOP",
            "WK_JewelersFileCard",
            "WK_KnifeMaintenanceLog",
            "WK_ScoutTroopToolCare",
            "WK_ShopApprenticeToolLog",
            "WK_WhetstoneSelectionRef",
        },
    },

    RangerDesk = {
        placeholder = "WK_Doc_RangerDesk",
        weight      = 16.6667,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_ApacheScoutTracking",
            "WK_BackyardForaging",
            "WK_BloodhoundHandlerCard",
            "WK_BowHunterCamoMan",
            "WK_DeerMovementRef",
            "WK_EdiblePlantsRef",
            "WK_EthnobotanyText",
            "WK_HerbalPharmacyEnc",
            "WK_HunterGatherersRef",
            "WK_KDFWRGameMgmtRef",
            "WK_KYCoonHunting",
            "WK_KYWildflowerGuide",
            "WK_NavySEALReconPamph",
            "WK_SARTrackingTraining",
            "WK_SignReadingNotes",
            "WK_StalkingWildAsparagus",
            "WK_ToxicPlantRef",
            "WK_TraditionalAppPlants",
            "WK_TurkeyHuntingRef",
            "WK_WildEdiblesCookbook",
            "WK_WildMushroomHunt",
            "WK_WildcraftHerbalistRef",
            "WK_WildlifeBiologyText",
            "WK_WildlifeTrackSignRef",
        },
    },

    RangerLockers = {
        placeholder = "WK_Doc_RangerLockers",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_ApacheScoutTracking",
            "WK_BloodhoundHandlerCard",
            "WK_BowHunterCamoMan",
            "WK_ConibearSetTechnique",
            "WK_DeerMovementRef",
            "WK_FootholdStakingRef",
            "WK_FoxHolerLureRecipes",
            "WK_FurAuctionGrading",
            "WK_FurbearerRef",
            "WK_KDFWRGameMgmtRef",
            "WK_KDFWRNuisanceWild",
            "WK_KDFWRTrapperRegs",
            "WK_KYBeaverTrapPamph",
            "WK_KYCoonHunting",
            "WK_MuskratPeltStretch",
            "WK_NTAFurHandlersGuide",
            "WK_NavySEALReconPamph",
            "WK_SARTrackingTraining",
            "WK_SignReadingNotes",
            "WK_TurkeyHuntingRef",
            "WK_USDAAnimalDamage",
            "WK_WildlifeBiologyText",
            "WK_WildlifeTrackSignRef",
            "WK_WildlifeTrappingGuide",
        },
    },

    HuntingLockers = {
        placeholder = "WK_Doc_HuntingLockers",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_BoyScoutRiflery",
            "WK_BullseyeMatchProgramme",
            "WK_ConibearSetTechnique",
            "WK_DefensiveHandgunRef",
            "WK_FBIQualScorebook",
            "WK_FootholdStakingRef",
            "WK_FoxHolerLureRecipes",
            "WK_FurAuctionGrading",
            "WK_FurbearerRef",
            "WK_HighPowerNewsletter",
            "WK_KCPDFirearmsQual",
            "WK_KDFWRNuisanceWild",
            "WK_KDFWRTrapperRegs",
            "WK_KYBeaverTrapPamph",
            "WK_KYConcealedCarryGuide",
            "WK_MuskratPeltStretch",
            "WK_NRAPistolInstructorMan",
            "WK_NTAFurHandlersGuide",
            "WK_RangeSafetyOfficerRef",
            "WK_SheriffQualLog",
            "WK_USDAAnimalDamage",
            "WK_USPSARulebook",
            "WK_VietnamRiflemanNotes",
            "WK_WildlifeTrappingGuide",
        },
    },

    PoliceLockers = {
        placeholder = "WK_Doc_PoliceLockers",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_BoyScoutRiflery",
            "WK_BullseyeMatchProgramme",
            "WK_DefensiveHandgunRef",
            "WK_FBIQualScorebook",
            "WK_HighPowerNewsletter",
            "WK_KCPDFirearmsQual",
            "WK_KYConcealedCarryGuide",
            "WK_NRAPistolInstructorMan",
            "WK_RangeSafetyOfficerRef",
            "WK_SheriffQualLog",
            "WK_USPSARulebook",
            "WK_VietnamRiflemanNotes",
        },
    },

    PoliceLibraryLegal = {
        placeholder = "WK_Doc_PoliceLibraryLegal",
        weight      = 8.3333,  -- specific tier, ~1 per 3 containers
        docs = {
            "WK_BoyScoutRiflery",
            "WK_BullseyeMatchProgramme",
            "WK_DefensiveHandgunRef",
            "WK_FBIQualScorebook",
            "WK_HighPowerNewsletter",
            "WK_KCPDFirearmsQual",
            "WK_KYConcealedCarryGuide",
            "WK_NRAPistolInstructorMan",
            "WK_RangeSafetyOfficerRef",
            "WK_SheriffQualLog",
            "WK_USPSARulebook",
            "WK_VietnamRiflemanNotes",
        },
    },
}

return WK_LootPools
